-- 0013_widget: per-tenant widget sites + anonymous-session table.
-- Each tenant can run the widget on one or more origins (e.g. www.brand.co.ke,
-- support.brand.co.ke). The widget back-end consults widget_sites to
-- validate the Origin header during the WebSocket upgrade.
--
-- visitor_id is a long-lived opaque cookie value set by the JS snippet
-- so a returning anonymous customer threads onto their previous
-- conversation. Identification escalates to a real customers row when
-- the user provides email/phone (consent banner before collection per
-- §15 of the plan).

CREATE TABLE widget_sites (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL REFERENCES tenants(id),
  origin            TEXT NOT NULL,        -- e.g. 'https://www.acme.co.ke'
  display_name      TEXT NOT NULL,
  -- Welcome message shown when a new visitor opens the widget. Plain
  -- text; templated server-side (no script injection from the JS).
  welcome_message   TEXT NOT NULL DEFAULT 'Hi! How can we help?',
  -- A short site-scoped key the JS snippet embeds in script tag attrs;
  -- mismatch on connect returns 401. Not a secret per se -- the
  -- Origin/CSRF check is the load-bearing defence -- but useful for
  -- rotating an embed without changing the script src.
  embed_key         TEXT NOT NULL,
  active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, origin)
);
CREATE INDEX widget_sites_origin_idx ON widget_sites (origin) WHERE active;

CREATE TRIGGER widget_sites_set_updated_at
  BEFORE UPDATE ON widget_sites
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Visitor sessions. The visitor_id is a UUID generated by the JS
-- client and stored in a first-party cookie; we map it to a customer
-- row when the visitor identifies themselves.
CREATE TABLE widget_visitors (
  id              UUID PRIMARY KEY,
  tenant_id       UUID NOT NULL REFERENCES tenants(id),
  site_id         UUID NOT NULL REFERENCES widget_sites(id),
  customer_id     UUID REFERENCES customers(id),
  first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_agent      TEXT,
  fingerprint     TEXT
);
CREATE INDEX widget_visitors_tenant_idx ON widget_visitors (tenant_id);
CREATE INDEX widget_visitors_customer_idx ON widget_visitors (customer_id) WHERE customer_id IS NOT NULL;
